import { Palette } from './types';

export const palettes: Palette[] = [
  {
    "description": "The perfect palette for all types of occasions.",
    "id": "1",
    "link": "https://www.sephora.com/product/born-to-run-eyeshadow-palette-P431748?icid2=products%20grid:p431748:product",
    "name": "Urban Decay Born to Run Eyeshadow Palette",
    "price": 49,
    "score": 6,
  },
  {
    "description": "This palette has some of the prettiest shades ever!",
    "id": "2",
    "link": "https://www.sephora.com/product/tarteist-pro-amazonian-clay-palette-P413177?icid2=products%20grid:p413177:product",
    "name": "Tarte Tarteist PRO Amazonian Clay Palette",
    "price": 49,
    "score": 9,
  },
  {
    "description": "A palette with fun pops of color and plenty of spunk.",
    "id": "3",
    "link": "https://jeffreestarcosmetics.com/collections/eyes/products/thirsty-palette",
    "name": "Jeffree Star Cosmetics Thirsty Palette",
    "price": 48,
    "score": 12,
  },
  {
    "description": "Large and in charge, this palette has any color you would ever need.",
    "id": "4",
    "link": "https://www.ulta.com/james-charles-palette?productId=pimprod2001848",
    "name": "Morphe The James Charles Palette",
    "price": 39,
    "score": 15,
  },
  {
    "description": "One word comes to mind�OBSESSED!!!",
    "id": "5",
    "link": "https://www.ulta.com/jaclyn-hill-eyeshadow-palette?productId=xlsImpprod17081131",
    "name": "Morphe Jaclyn Hill Eyeshadow Palette",
    "price": 38,
    "score": 18,
  },
  {
    "description": "A gorgeous palette for the ultimate purple fantasy.",
    "id": "6",
    "link": "https://www.sephora.com/product/obsessions-gemstone-eyeshadow-palette-P45188659?icid2=products%20grid:p45188659:product&skuId=2137271",
    "name": "Huda Beauty Obsessions Eyeshadow Palette in Amethyst",
    "price": 27,
    "score": 21,
  },
  {
    "description": "A fun palette to brighten up your day that lets you shine.",
    "id": "7",
    "link": "https://www.ulta.com/aurora-lights-18-color-baked-eyeshadow-palette?productId=xlsImpprod18771165",
    "name": "BH Cosmetics Aurora Lights",
    "price": 18,
    "score": 24,
  },
  {
    "description": "A palette with beautiful colors for a girl on a budget.",
    "id": "8",
    "link": "https://www.ulta.com/reloaded-palette?productId=xlsImpprod17681065",
    "name": "Makeup Revolution Reloaded Palette Division",
    "price": 7,
    "score": 27,
  },
  {
    "description": "A beautiful palette to create both everyday looks and some serious red carpet glam.",
    "id": "9",
    "link": "https://www.sephora.com/product/the-new-nude-eyeshadow-palette-P43818047",
    "name": "Huda Beauty The New Nude Palette",
    "price": 65,
    "score": 30,
  },
  {
    "description": "A palette with enough shimmers to get you noticed.",
    "id": "10",
    "link": "https://www.sephora.com/product/chocolate-gold-eyeshadow-palette-P426848?icid2=products%20grid:p426848:product",
    "name": "Too Faced Chocolate Gold Eyeshadow Palette",
    "price": 49,
    "score": 33,
  },
  {
    "description": "It looks good enough to eat! Want to take a bite?",
    "id": "11",
    "link": "https://www.ulta.com/naked-cherry-eyeshadow-palette?productId=pimprod2000806",
    "name": "Urban Decay Naked Cherry Eyeshadow Palette",
    "price": 49,
    "score": 36,
  },
  {
    "description": "The perfect palette to create any number of looks that are either simple or sassy.",
    "id": "12",
    "link": "https://www.sephora.com/product/like-boss-palette-P429925?icid2=products%20grid:p429925:product",
    "name": "Violet Voss Like a Boss Pro Eyeshadow Palette",
    "price": 45,
    "score": 39,
  },
  {
    "description": "A palette that lives up to its name, with gorgeous metallics and blendable mattes.",
    "id": "13",
    "link": "https://www.ulta.com/sultry-eyeshadow-palette?productId=pimprod2000871",
    "name": "Anastasia Beverly Hills Sultry Palette",
    "price": 45,
    "score": 42,
  },
  {
    "description": "Perfect to achieve your everyday glam looks!",
    "id": "14",
    "link": "https://www.ulta.com/soft-glam-eyeshadow-palette?productId=xlsImpprod17841007",
    "name": "Anastasia Beverly Hills Soft Glam Eyeshadow Palette",
    "price": 42,
    "score": 45,
  },
  {
    "description": "From natural to dramatic smoky looks, this palette is a great addition to anyone's makeup collection.",
    "id": "15",
    "link": "https://www.ulta.com/35f-fall-into-frost-eyeshadow-palette?productId=xlsImpprod17081135",
    "name": "Morphe 35F Fall into Frost Eyeshadow Palette",
    "price": 24,
    "score": 48,
  },
  {
    "description": "A palette with some of the prettiest neutral shades around!",
    "id": "16",
    "link": "https://www.ulta.com/sweet-peach-eyeshadow-palette?productId=xlsImpprod13941029",
    "name": "Too Faced Sweet Peach Eyeshadow Palette",
    "price": 49,
    "score": 51,
  },
  {
    "description": "A must-have matte palette that lets you bring dimension to any eye look.",
    "id": "17",
    "link": "https://www.sephora.com/product/shade-light-eye-contour-palette-P413457?icid2=products%20grid:p413457:product",
    "name": "Kat Von D Shade + Light Eye Contour Palette",
    "price": 48,
    "score": 54,
  },
  {
    "description": "A great palette to create the most beautiful, classic looks.",
    "id": "18",
    "link": "https://www.ulta.com/tartelette-2-in-bloom-clay-eyeshadow-palette?productId=xlsImpprod13281007",
    "name": "Tartelette 2 In Bloom Clay Eyeshadow Palette",
    "price": 39,
    "score": 57,
  },
  {
    "description": "An adorable palette with beautiful rose gold hues.",
    "id": "19",
    "link": "https://www.ulta.com/smashbox-vlada-cover-shot-petal-metal-eyeshadow-palette?productId=xlsImpprod18121009",
    "name": "Smashbox + Vlada Cover Shot: Petal Metal Eye Shadow",
    "price": 29,
    "score": 60,
  },
  {
    "description": "A fun palette for those cool-toned queens.",
    "id": "20",
    "link": "https://www.ulta.com/fame-pressed-powder-eyeshadow-palette?productId=xlsImpprod18951011&sku=2535053&_requestid=5236933",
    "name": "ColourPop Fame Pressed Powder Eyeshadow Palette",
    "price": 22,
    "score": 63,
  },
  {
    "description": "A beautiful neutral palette with shimmery kick.",
    "id": "21",
    "link": "https://www.ulta.com/warrior-eyeshadow-palette?productId=xlsImpprod18771145",
    "name": "Juvia's Place The Warrior Eyeshadow Palette",
    "price": 20,
    "score": 66,
  },
  {
    "description": "A cute little palette you can take anywhere!",
    "id": "22",
    "link": "https://www.sephora.com/product/tartlette-flirt-eyeshadow-palette-P424438?icid2=products%20grid:p424438:product",
    "name": "Tartelette Flirt Eyeshadow Palette",
    "price": 19,
    "score": 69,
  },
  {
    "description": "A cute palette for everyday looks.",
    "id": "23",
    "link": "https://www.ulta.com/warm-neutrals-ultimate-shadow-palette?productId=xlsImpprod13901019",
    "name": "NYX Warm Neutrals Ultimate Shadow Palette",
    "price": 18,
    "score": 72,
  },
  {
    "description": "A great drugstore find to keep you looking elegant.",
    "id": "24",
    "link": "https://www.ulta.com/shimmer-shade-eyeshadow-palette?productId=xlsImpprod17631409",
    "name": "Flower Beauty Shimmer and Shade Eyeshadow Palette Golden Natural",
    "price": 16.99,
    "score": 75,
  },
  {
    "description": "A palette that is as sweet as its name.",
    "id": "25",
    "link": "https://colourpop.com/products/brown-sugar",
    "name": "ColourPop Brown Sugar Pressed Powder Shadow Palette",
    "price": 12,
    "score": 78,
  }
]
