# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'paletteFinder' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for paletteFinder

  

  platform :ios, '9.0'

  target 'paletteFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'paletteFinder-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for paletteFinder-tvOS

  target 'paletteFinder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
