# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactnativestarter' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  pod 'Firebase/Database', '~> 5.11.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativestarter

  

  platform :ios, '9.0'
  target 'reactnativestarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativestarter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativestarter-tvOS

  target 'reactnativestarter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
